export const initialColumns: Columns = {
  backlog: {
    name: 'Backlog',
    description: "This item hasn't been started",
    limit: 15,
    color: 'border-green-600',
    items: [
      { id: '1', content: 'Ability to buy plain items' },
      { id: '2', content: 'Calculate Delivery Fee based on Items' },
      { id: '3', content: 'Calculate Delivery Fee based on Items' },
      { id: '4', content: 'Calculate Delivery Fee based on Items' },
      { id: '5', content: 'Calculate Delivery Fee based on Items' },
      { id: '6', content: 'Calculate Delivery Fee based on Items' },
      { id: '7', content: 'Calculate Delivery Fee based on Items' },
      { id: '8', content: 'Calculate Delivery Fee based on Items' },
      { id: '9', content: 'Calculate Delivery Fee based on Items' },
      { id: '10', content: 'Calculate Delivery Fee based on Items' },
    ],
  },
  ready: {
    name: 'Ready',
    description: 'This is ready to be picked up',
    limit: 3,
    color: 'border-blue-600',
    items: [{ id: '3', content: 'Creating a Quote for custom order' }],
  },
  inProgress: {
    name: 'In Progress',
    description: 'This is actively being worked on',
    limit: 3,
    color: 'border-yellow-600',
    items: [
      { id: '4', content: 'Loading orders and grouping order by status' },
    ],
  },
  inReview: {
    name: 'In Review',
    description: 'This item is being reviewed',
    limit: 5,
    color: 'border-indigo-600',
    items: [{ id: '5', content: 'Admin Authentication' }],
  },
  done: {
    name: 'Done',
    description: 'This item has been completed',
    limit: 25,
    color: 'border-orange-600',
    items: [{ id: '6', content: 'User’s Auth completion and password reset' }],
  },
};
